# Generated by Django 2.2.1 on 2019-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta_Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Título')),
                ('tipo_pergunta_resposta', models.CharField(choices=[('enquete', 'enquete'), ('questionario', 'questionario')], max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
