# Generated by Django 2.2.1 on 2019-06-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pergunta_resposta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pergunta_Resposta',
            new_name='PerguntaResposta',
        ),
    ]
