# Generated by Django 2.2.1 on 2019-06-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190602_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaresposta',
            options={'managed': True, 'verbose_name': 'PerguntaResposta', 'verbose_name_plural': 'PerguntaRespostas'},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='perguntaresposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PerguntaResposta'),
        ),
        migrations.AlterField(
            model_name='perguntaresposta',
            name='tipo_pergunta_resposta',
            field=models.CharField(choices=[('enquete', 'enquete'), ('questionario', 'questionario'), ('prova', 'prova')], max_length=15, verbose_name='Tipo'),
        ),
    ]
